package testdirectorio;

/**
 * @author Leandro Heredia
 */
public class PanelDirectorio extends javax.swing.JFrame {
    
    private static Directorio dire = new Directorio();
    
    /**
     * Creates new form PanelDirectorio
     */
    public PanelDirectorio() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmDirectorio = new javax.swing.JMenu();
        jmAgregarCliente = new javax.swing.JMenuItem();
        jmBuscarCliente = new javax.swing.JMenuItem();
        jmBorrarCliente = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );

        jmDirectorio.setText("Directorio");

        jmAgregarCliente.setText("Agregar Cliente");
        jmAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarClienteActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmAgregarCliente);

        jmBuscarCliente.setText("Buscar Cliente");
        jmBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBuscarClienteActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmBuscarCliente);

        jmBorrarCliente.setText("Borrar Cliente");
        jmBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBorrarClienteActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmBorrarCliente);

        jMenuBar1.add(jmDirectorio);

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jmAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarClienteActionPerformed
        // TODO add your handling code here:
        AgregarCliente agregar = new AgregarCliente();

        escritorio.removeAll();
        escritorio.repaint();

        agregar.setVisible(true);
        escritorio.add(agregar);
        escritorio.moveToFront(agregar);
    }//GEN-LAST:event_jmAgregarClienteActionPerformed
    
    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmSalirActionPerformed
    
    private void jmBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBuscarClienteActionPerformed
        // TODO add your handling code here:
        BuscarCliente buscar = new BuscarCliente();

        escritorio.removeAll();
        escritorio.repaint();

        buscar.setVisible(true);
        escritorio.add(buscar);
        escritorio.moveToFront(buscar);
    }//GEN-LAST:event_jmBuscarClienteActionPerformed
    
    private void jmBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBorrarClienteActionPerformed
        // TODO add your handling code here:
        BorrarCliente borrar = new BorrarCliente();

        escritorio.removeAll();
        escritorio.repaint();

        borrar.setVisible(true);
        escritorio.add(borrar);
        escritorio.moveToFront(borrar);
    }//GEN-LAST:event_jmBorrarClienteActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDirectorio().setVisible(true);
            }
        });
    }
    
    public static Directorio getDirectorio() {
        return dire;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmAgregarCliente;
    private javax.swing.JMenuItem jmBorrarCliente;
    private javax.swing.JMenuItem jmBuscarCliente;
    private javax.swing.JMenu jmDirectorio;
    private javax.swing.JMenu jmSalir;
    // End of variables declaration//GEN-END:variables
}
